package com.heavenscode.rac.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AutocaretimetableAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAutocaretimetableAllPropertiesEquals(Autocaretimetable expected, Autocaretimetable actual) {
        assertAutocaretimetableAutoGeneratedPropertiesEquals(expected, actual);
        assertAutocaretimetableAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAutocaretimetableAllUpdatablePropertiesEquals(Autocaretimetable expected, Autocaretimetable actual) {
        assertAutocaretimetableUpdatableFieldsEquals(expected, actual);
        assertAutocaretimetableUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAutocaretimetableAutoGeneratedPropertiesEquals(Autocaretimetable expected, Autocaretimetable actual) {
        assertThat(expected)
            .as("Verify Autocaretimetable auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAutocaretimetableUpdatableFieldsEquals(Autocaretimetable expected, Autocaretimetable actual) {
        assertThat(expected)
            .as("Verify Autocaretimetable relevant properties")
            .satisfies(e -> assertThat(e.getHoisttypeid()).as("check hoisttypeid").isEqualTo(actual.getHoisttypeid()))
            .satisfies(e -> assertThat(e.getHoisttypename()).as("check hoisttypename").isEqualTo(actual.getHoisttypename()))
            .satisfies(e -> assertThat(e.getHoisttime()).as("check hoisttime").isEqualTo(actual.getHoisttime()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAutocaretimetableUpdatableRelationshipsEquals(Autocaretimetable expected, Autocaretimetable actual) {}
}
