package com.heavenscode.rac.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AutocarejobinimagesAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAutocarejobinimagesAllPropertiesEquals(Autocarejobinimages expected, Autocarejobinimages actual) {
        assertAutocarejobinimagesAutoGeneratedPropertiesEquals(expected, actual);
        assertAutocarejobinimagesAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAutocarejobinimagesAllUpdatablePropertiesEquals(Autocarejobinimages expected, Autocarejobinimages actual) {
        assertAutocarejobinimagesUpdatableFieldsEquals(expected, actual);
        assertAutocarejobinimagesUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAutocarejobinimagesAutoGeneratedPropertiesEquals(Autocarejobinimages expected, Autocarejobinimages actual) {
        assertThat(expected)
            .as("Verify Autocarejobinimages auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAutocarejobinimagesUpdatableFieldsEquals(Autocarejobinimages expected, Autocarejobinimages actual) {
        assertThat(expected)
            .as("Verify Autocarejobinimages relevant properties")
            .satisfies(e -> assertThat(e.getJobid()).as("check jobid").isEqualTo(actual.getJobid()))
            .satisfies(e -> assertThat(e.getImagefolder()).as("check imagefolder").isEqualTo(actual.getImagefolder()))
            .satisfies(e -> assertThat(e.getImagename()).as("check imagename").isEqualTo(actual.getImagename()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAutocarejobinimagesUpdatableRelationshipsEquals(Autocarejobinimages expected, Autocarejobinimages actual) {}
}
