package com.heavenscode.rac.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BanksAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBanksAllPropertiesEquals(Banks expected, Banks actual) {
        assertBanksAutoGeneratedPropertiesEquals(expected, actual);
        assertBanksAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBanksAllUpdatablePropertiesEquals(Banks expected, Banks actual) {
        assertBanksUpdatableFieldsEquals(expected, actual);
        assertBanksUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBanksAutoGeneratedPropertiesEquals(Banks expected, Banks actual) {
        assertThat(expected)
            .as("Verify Banks auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBanksUpdatableFieldsEquals(Banks expected, Banks actual) {
        assertThat(expected)
            .as("Verify Banks relevant properties")
            .satisfies(e -> assertThat(e.getCode()).as("check code").isEqualTo(actual.getCode()))
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()))
            .satisfies(e -> assertThat(e.getLmu()).as("check lmu").isEqualTo(actual.getLmu()))
            .satisfies(e -> assertThat(e.getLmd()).as("check lmd").isEqualTo(actual.getLmd()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBanksUpdatableRelationshipsEquals(Banks expected, Banks actual) {}
}
