package com.heavenscode.rac.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EmpSectiontblAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmpSectiontblAllPropertiesEquals(EmpSectiontbl expected, EmpSectiontbl actual) {
        assertEmpSectiontblAutoGeneratedPropertiesEquals(expected, actual);
        assertEmpSectiontblAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmpSectiontblAllUpdatablePropertiesEquals(EmpSectiontbl expected, EmpSectiontbl actual) {
        assertEmpSectiontblUpdatableFieldsEquals(expected, actual);
        assertEmpSectiontblUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmpSectiontblAutoGeneratedPropertiesEquals(EmpSectiontbl expected, EmpSectiontbl actual) {
        assertThat(expected)
            .as("Verify EmpSectiontbl auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmpSectiontblUpdatableFieldsEquals(EmpSectiontbl expected, EmpSectiontbl actual) {
        assertThat(expected)
            .as("Verify EmpSectiontbl relevant properties")
            .satisfies(e -> assertThat(e.getEmpid()).as("check empid").isEqualTo(actual.getEmpid()))
            .satisfies(e -> assertThat(e.getSectionid()).as("check sectionid").isEqualTo(actual.getSectionid()))
            .satisfies(e -> assertThat(e.getLmd()).as("check lmd").isEqualTo(actual.getLmd()))
            .satisfies(e -> assertThat(e.getLmu()).as("check lmu").isEqualTo(actual.getLmu()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmpSectiontblUpdatableRelationshipsEquals(EmpSectiontbl expected, EmpSectiontbl actual) {}
}
