package com.heavenscode.rac.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class HoisttypeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHoisttypeAllPropertiesEquals(Hoisttype expected, Hoisttype actual) {
        assertHoisttypeAutoGeneratedPropertiesEquals(expected, actual);
        assertHoisttypeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHoisttypeAllUpdatablePropertiesEquals(Hoisttype expected, Hoisttype actual) {
        assertHoisttypeUpdatableFieldsEquals(expected, actual);
        assertHoisttypeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHoisttypeAutoGeneratedPropertiesEquals(Hoisttype expected, Hoisttype actual) {
        assertThat(expected)
            .as("Verify Hoisttype auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHoisttypeUpdatableFieldsEquals(Hoisttype expected, Hoisttype actual) {
        assertThat(expected)
            .as("Verify Hoisttype relevant properties")
            .satisfies(e -> assertThat(e.getHoisttype()).as("check hoisttype").isEqualTo(actual.getHoisttype()))
            .satisfies(e -> assertThat(e.getLmu()).as("check lmu").isEqualTo(actual.getLmu()))
            .satisfies(e -> assertThat(e.getLmd()).as("check lmd").isEqualTo(actual.getLmd()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHoisttypeUpdatableRelationshipsEquals(Hoisttype expected, Hoisttype actual) {}
}
