import dayjs from 'dayjs/esm';

import { ICustomer, NewCustomer } from './customer.model';

export const sampleWithRequiredData: ICustomer = {
  id: 7725,
};

export const sampleWithPartialData: ICustomer = {
  id: 31827,
  namewithinitials: 'per because',
  callingname: 'downlink careless',
  nicno: 'correspondent hoax since',
  nicissueddate: dayjs('2024-08-14'),
  dateofbirth: dayjs('2024-08-13'),
  bloodgroup: 'vice',
  gender: 'ack how',
  maritalstatus: 'page gee if',
  nationality: 28072,
  businessregdate: dayjs('2024-08-13'),
  profilepicturepath: 'aw circular the',
  residencehouseno: 'snarling now through',
  residenceaddress: 'times honorable',
  residencephone: 'through pace',
  businesslocationno: 'uh-huh victoriously ew',
  businessaddress: 'behold',
  businessphone1: 'hence smith barber',
  businessmobile: 'why concerning atop',
  contactpersonphone: 'yuck slowly till',
  contactpersonmobile: 'alongside',
  registrationdate: dayjs('2024-08-14T10:25'),
  isinternalcustomer: 24380,
  lmu: 18336,
  creditlimit: 16724.01,
  hassecuritydeposit: true,
  securitydepositamount: 9243.19,
  cashlastinvoicebeforeload: true,
  paybycredit: false,
  creditpaymentbydays: 7674,
  haspurchasingdeposit: false,
  hassecuritydepositbond: true,
  employerdesignation: 'likewise',
  previousemployername: 'perpetrate out tractor',
  previousemployeraddress: 'swamp dread',
  previousindustry: 'athwart deplane huzzah',
  previousperiod: 'bah cafe',
  previouspositions: 'drain bouncy',
  previousresionforleaving: 'retouching huzzah whenever',
  hascreaditlimit: false,
  accountcode: 'pfft amidst',
  isregistered: false,
  vatregnumber: 'pro wheel',
  creditperiod: 23297,
};

export const sampleWithFullData: ICustomer = {
  id: 14661,
  customertype: 667,
  code: 'amongst flawed like',
  title: 'wrongly furiously',
  namewithinitials: 'aggradation assured apud',
  fullname: 'gee',
  callingname: 'uh-huh brightly',
  nicno: 'beside for coolly',
  nicissueddate: dayjs('2024-08-14'),
  dateofbirth: dayjs('2024-08-14'),
  bloodgroup: 'whenever popularity',
  gender: 'but unless domesticate',
  maritalstatus: 'mama brr anticipation',
  marrieddate: dayjs('2024-08-13'),
  nationality: 8007,
  territory: 'beyond uniform',
  religion: 17999,
  team: 'trepan conscientise',
  businessname: 'deluge rebel ceramics',
  businessregdate: dayjs('2024-08-13'),
  businessregno: 'inexperienced',
  profilepicturepath: 'before',
  residencehouseno: 'prime assembly whoever',
  residenceaddress: 'weakly',
  residencecity: 'searchingly giddy',
  residencephone: 'keenly reward weakly',
  businesslocationno: 'mobile past avail',
  businessaddress: 'truly',
  businesscity: 'e-mail loyal oof',
  businessphone1: 'instead powerful sequence',
  businessphone2: 'larder',
  businessmobile: 'hence hence uh-huh',
  businessfax: 'keenly yesterday sorbet',
  businessemail: 'permission',
  businessprovinceid: 9755,
  businessdistrictid: 2166,
  contactpersonname: 'dissemination',
  contactpersonphone: 'gosh',
  contactpersonmobile: 'whether testify without',
  contactpersonemail: 'since',
  rootmappath: 'meh ace',
  website: 'which',
  registrationdate: dayjs('2024-08-13T13:40'),
  isactive: 3161,
  isinternalcustomer: 23608,
  description: 'psst leafy',
  lmu: 20621,
  lmd: dayjs('2024-08-14T03:57'),
  maximumdiscount: 5307.05,
  creditlimit: 7689.8,
  hassecuritydeposit: false,
  securitydepositamount: 26135.27,
  paybycash: true,
  cashpaymentbeforeload: true,
  cashlastinvoicebeforeload: true,
  paybycredit: false,
  creditoneweekcheck: false,
  creditpaymentbydays: 13353,
  haspurchasingdeposit: true,
  hassecuritydepositbond: false,
  hasassestsdeposit: true,
  customerrootmappath: 'incidentally',
  employername: 'browse',
  employeraddress: 'quaint',
  employerphone: 'hole',
  employerdesignation: 'phew till',
  previousemployername: 'now automation whoever',
  previousemployeraddress: 'gee considering wing',
  previousindustry: 'provided onto boohoo',
  previousperiod: 'gullible meh acclaimed',
  previouspositions: 'drat',
  previousresionforleaving: 'mind worthwhile',
  hascreaditlimit: true,
  accountid: 10305,
  accountcode: 'an',
  isregistered: false,
  vatregnumber: 'fritter sans sail',
  tinnumber: 'fancy',
  lat: 'shy ha',
  lon: 'geez beside',
  creditperiod: 4424,
};

export const sampleWithNewData: NewCustomer = {
  id: null,
};

Object.freeze(sampleWithNewData);
Object.freeze(sampleWithRequiredData);
Object.freeze(sampleWithPartialData);
Object.freeze(sampleWithFullData);
